# Generated by Django 4.1.4 on 2022-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.SlugField()),
                ('created_at', models.DateTimeField(editable=False)),
                ('done_at', models.DateTimeField(null=True)),
                ('udpated_at', models.DateTimeField()),
                ('delete_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
