# Generated by Django 4.1.4 on 2022-12-07 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(),
        ),
    ]
