# Generated by Django 4.1.4 on 2022-12-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_photo_alter_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
