# Generated by Django 4.1.4 on 2022-12-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
