# Generated by Django 4.1.4 on 2022-12-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_alter_project_photo_alter_project_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photo',
            field=models.URLField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(max_length=5000),
        ),
    ]
